apiVersion: apps/v1
kind: Deployment
metadata:
  name: ki-site
  namespace: ki-site
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ki-site
  template:
    metadata:
      labels:
        app: ki-site
    spec:
      automountServiceAccountToken: false
      containers:
        - name: ki-site
          image: ghcr.io/fhswf/ki.site:1.0.2
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          env:
            - name: PUBLIC_RELEASE
              value: 1.0.2
            - name: PUBLIC_BUILD_SHA
              value: 625000155b069b9f7f7a62186fe60fd2213c9b13
          resources:
            limits:
              memory: 256Mi
              cpu: 500m
            requests:
              memory: 64Mi
              cpu: 250m
