apiVersion: apps/v1
kind: Deployment
metadata:
  name: ki-site
  namespace: ki-site
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ki-site
  template:
    metadata:
      labels:
        app: ki-site
    spec:
      automountServiceAccountToken: false
      containers:
        - name: ki-site
          image: ghcr.io/fhswf/ki.site:1.2.0
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          env:
            - name: PUBLIC_RELEASE
              value: 1.2.0
            - name: PUBLIC_BUILD_SHA
              value: 36528dc1003aaedfa8777f0e09d11879d10e3a4f
          resources:
            limits:
              memory: 256Mi
              cpu: 500m
            requests:
              memory: 64Mi
              cpu: 250m
