on:
  push:
    branches:
      - main
jobs:
  docker:
    timeout-minutes: 10
    runs-on: self-hosted

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Start containers
        run: docker compose up -d --build
